version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    volumes:
      - db_volume:/var/lib/mysql # バックアップ
    env_file:
      - ./docker/mysql/db-variable.env #環境変数の設定
    restart: always

  app:
    build:
      context: ./docker/php-apache/
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./docker/php-apache/src/:/var/www/html
    environment:
      - VIRTUAL_HOST=${DMAIN}
      - LETSENCRYPT_HOST=${DMAIN}
    networks:
      - nginx-proxy_default
    # ports:
    #   - 80:80
    depends_on:
      - db


volumes:
  db_volume:

networks:
  nginx-proxy_default:
    external: true
